import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router";
import { Activity, ArrowUpRight, BrainCircuit, BriefcaseBusiness, Bot, Building2, Clock3, Cpu, FileText, Gauge, LockKeyhole, Network, Newspaper, PhoneCall, Radio, RefreshCw, Rocket, ScanLine, ShieldCheck, Sparkles, Terminal, Zap } from "lucide-react";
import { api, type StatusResponse } from "@/lib/api";

const departments = [
  ["marketing","Marketing","Content · Social · SEO · Websites · Creative"],
  ["security","Security","Cybersecurity · Threat intel · Monitoring · CyberLab"],
  ["research-intelligence","Research & Intelligence","Web research · Markets · Competition · Data"],
  ["engineering","Engineering","Software · APIs · Infrastructure · Deployment"],
  ["sales-leads","Sales & Leads","Lead generation · Qualification · CRM · Outreach"],
  ["finance","Finance","Revenue · Costs · P&L · Opportunity analysis"],
  ["operations","Operations","Automation · Agents · Scheduling · Communications"],
] as const;

const businesses = [
  ["news-media","News Media Engine","DEVELOPMENT","Research → originality → editorial → SEO → publish → monetise",Newspaper],
  ["bond-leads","Bond Prospect Engine","PROSPECTING","Intent discovery → interest capture → scoring → controlled review queue",BriefcaseBusiness],
  ["telephone-agent","Telephone Agent Capability","FOUNDATION","Operations capability available to business plugins",PhoneCall],
] as const;

function Metric({label,value,detail,icon:Icon,accent=false}:{label:string;value:string;detail:string;icon:React.ComponentType<{className?:string}>;accent?:boolean}) {
  return <div className={"group relative overflow-hidden rounded-2xl border " + (accent ? "border-cyan-400/30" : "border-white/[0.08]") + " bg-white/[0.035] p-4 backdrop-blur-xl transition duration-300 hover:-translate-y-0.5 hover:border-cyan-300/30"}>
    <div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-cyan-400/10 blur-2xl" />
    <div className="relative flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-white/40">{label}</span><Icon className={"h-4 w-4 " + (accent ? "text-cyan-300" : "text-white/35")} /></div>
    <div className="relative mt-3 text-xl font-semibold tracking-tight text-white">{value}</div><div className="relative mt-1 text-[11px] text-white/40">{detail}</div>
  </div>;
}

function Panel({children,className=""}:{children:React.ReactNode;className?:string}) {
  return <section className={"rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 backdrop-blur-xl " + className}>{children}</section>;
}

export default function GuardianCommandPage() {
  const [status,setStatus]=useState<StatusResponse|null>(null);
  const [refreshing,setRefreshing]=useState(false);
  const [boot,setBoot]=useState(0);
  const load=async()=>{setRefreshing(true);try{setStatus(await api.getStatus())}finally{setRefreshing(false)}};
  useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15000);const b=window.setInterval(()=>setBoot(v=>(v+1)%100),800);return()=>{window.clearInterval(t);window.clearInterval(b)}},[]);
  const gateway=status?.gateway_running;
  const sessions=status?.active_sessions??0;
  const uptime=useMemo(()=>gateway?"NOMINAL":"ATTENTION",[gateway]);

  return <div className="relative min-h-full overflow-hidden bg-[#03070b] text-white">
    <style>{"@keyframes gp{0%,100%{opacity:.35;transform:scale(.96)}50%{opacity:.9;transform:scale(1.04)}}@keyframes gs{0%{transform:translateY(-100%)}100%{transform:translateY(100vh)}}@keyframes gd{0%,100%{transform:translate3d(0,0,0)}50%{transform:translate3d(12px,-8px,0)}}.guardian-grid{background-image:linear-gradient(rgba(70,220,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(70,220,255,.035) 1px,transparent 1px);background-size:42px 42px}"}</style>
    <div className="pointer-events-none absolute inset-0 guardian-grid" />
    <div className="pointer-events-none absolute -left-32 -top-32 h-[520px] w-[520px] rounded-full bg-cyan-500/10 blur-[120px]" style={{animation:"gd 9s ease-in-out infinite"}} />
    <div className="pointer-events-none absolute -right-40 top-1/3 h-[620px] w-[620px] rounded-full bg-blue-600/10 blur-[140px]" style={{animation:"gd 12s ease-in-out infinite reverse"}} />
    <div className="pointer-events-none absolute left-0 right-0 top-0 h-px bg-cyan-300/30 shadow-[0_0_30px_4px_rgba(34,211,238,.15)]" style={{animation:"gs 8s linear infinite"}} />
    <main className="relative mx-auto max-w-[1700px] px-4 py-5 md:px-7 md:py-7 xl:px-10">
      <header className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-4"><div className="relative flex h-12 w-12 items-center justify-center rounded-2xl border border-cyan-300/30 bg-cyan-300/[0.07] shadow-[0_0_35px_rgba(34,211,238,.12)]"><ShieldCheck className="h-6 w-6 text-cyan-200"/><span className="absolute inset-0 rounded-2xl border border-cyan-300/20" style={{animation:"gp 2.8s ease-in-out infinite"}}/></div><div><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.35em] text-cyan-300/70"><Sparkles className="h-3 w-3"/> Autonomous Business Operating System</div><h1 className="mt-1 text-2xl font-semibold tracking-[-0.03em] md:text-3xl">GUARDIAN <span className="font-light text-white/35">OS</span></h1></div></div>
        <div className="flex items-center gap-3"><div className="hidden items-center gap-3 rounded-full border border-white/[0.08] bg-white/[0.025] px-4 py-2 md:flex"><span className={"h-2 w-2 rounded-full " + (gateway ? "bg-emerald-300 shadow-[0_0_12px_rgba(110,231,183,.9)]" : "bg-amber-300")}/><span className="text-[10px] font-semibold uppercase tracking-[0.2em] text-white/55">{uptime}</span><span className="text-[10px] text-white/25">NODE 02</span></div><button onClick={()=>void load()} disabled={refreshing} className="rounded-xl border border-white/10 bg-white/[0.035] p-2.5 text-white/55 transition hover:border-cyan-300/30 hover:text-cyan-200 disabled:opacity-40"><RefreshCw className={"h-4 w-4 " + (refreshing ? "animate-spin" : "")}/></button></div>
      </header>
      <section className="relative mb-6 overflow-hidden rounded-[28px] border border-cyan-300/15 bg-gradient-to-br from-cyan-300/[0.07] via-white/[0.025] to-blue-500/[0.04] p-6 shadow-[0_25px_100px_rgba(0,0,0,.35)] md:p-8">
        <div className="relative grid gap-8 lg:grid-cols-[1fr_360px] lg:items-center"><div><div className="mb-4 flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.3em] text-cyan-200/65"><Radio className="h-3.5 w-3.5"/> Guardian Command Centre · Live Telemetry</div><h2 className="max-w-3xl text-3xl font-semibold leading-[1.05] tracking-[-0.04em] md:text-5xl">One intelligence layer.<br/><span className="text-cyan-200">Every business under control.</span></h2><p className="mt-5 max-w-2xl text-sm leading-6 text-white/45">Guardian Core orchestrates the OS. Departments provide capabilities. Agents perform them. Business plugins combine them into revenue engines.</p><div className="mt-6 flex flex-wrap gap-2">{[["/chat","Command",Terminal],["/sessions","Operations",Activity],["/cron","Autonomy",Clock3],["/plugins","Plugin System",Rocket]].map(([to,label,Icon])=><Link key={String(to)} to={String(to)} className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-3.5 py-2.5 text-[10px] font-bold uppercase tracking-widest text-white/65 transition hover:border-cyan-300/30 hover:text-cyan-100"><Icon className="h-3.5 w-3.5 text-cyan-300/70"/>{String(label)}</Link>)}</div></div>
          <div className="relative mx-auto w-full max-w-[330px]"><div className="aspect-square rounded-full border border-cyan-300/10 bg-cyan-300/[0.02] p-8 shadow-[inset_0_0_80px_rgba(34,211,238,.05)]"><div className="relative flex h-full items-center justify-center rounded-full border border-cyan-300/15"><div className="absolute inset-[18%] rounded-full border border-cyan-300/20"/><div className="absolute inset-[32%] rounded-full border border-cyan-300/25 bg-cyan-300/[0.04]" style={{animation:"gp 3s ease-in-out infinite"}}/><div className="relative flex flex-col items-center"><BrainCircuit className="h-10 w-10 text-cyan-200"/><span className="mt-2 text-[9px] font-bold uppercase tracking-[0.3em] text-white/45">Guardian Core</span><span className="mt-1 text-xs font-semibold text-cyan-100">ONLINE</span></div></div></div><div className="absolute -bottom-2 left-1/2 -translate-x-1/2 rounded-full border border-white/10 bg-[#050a0f]/90 px-3 py-1.5 text-[8px] font-bold uppercase tracking-[0.25em] text-white/35 backdrop-blur-xl">LOCAL-FIRST / CONTROLLED</div></div>
        </div>
      </section>
      <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Gateway" value={gateway?"ONLINE":"CHECKING"} detail={status?.gateway_state??"Awaiting telemetry"} icon={Network} accent={!!gateway}/><Metric label="Intelligence" value="QWEN3 · OLLAMA" detail={status ? "Hermes " + status.version + " · local runtime" : "Loading local runtime"} icon={Bot} accent/><Metric label="Active Sessions" value={String(sessions).padStart(2,"0")} detail="Autonomous execution channels" icon={Activity}/><Metric label="Safety Layer" value="LOCKED" detail="Live financial execution disabled" icon={LockKeyhole}/></section>
      <div className="mb-3 flex items-end justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[0.28em] text-cyan-300/55">Organisation</div><h3 className="mt-1 text-lg font-semibold">Departments</h3></div><span className="text-[9px] uppercase tracking-widest text-white/25">7 capability domains</span></div>
      <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{departments.map(([id,name,caps],i)=><Link key={id} to={"/guardian/department/" + id} className="group rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4 transition hover:-translate-y-1 hover:border-cyan-300/25 hover:bg-cyan-300/[0.035]"><div className="flex items-center justify-between"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-white/[0.04]"><Building2 className="h-4 w-4 text-cyan-300"/></div><span className="text-[9px] font-bold text-white/20">D0{i+1}</span></div><div className="mt-4 text-sm font-semibold text-white/85">{name}</div><div className="mt-2 text-[10px] leading-5 text-white/35">{caps}</div><div className="mt-4 flex items-center gap-1 text-[9px] font-bold uppercase tracking-widest text-cyan-300/50 group-hover:text-cyan-200">Open department <ArrowUpRight className="h-3 w-3"/></div></Link>)}</section>
      <div className="mb-3 flex items-end justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[0.28em] text-cyan-300/55">Business Layer</div><h3 className="mt-1 text-lg font-semibold">Active Business Engines</h3></div><span className="text-[9px] uppercase tracking-widest text-white/25">Plugins, not departments</span></div>
      <section className="mb-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{businesses.map(([id,title,state,text,Icon])=><Link key={id} to={id==="news-media"?"/guardian/business/news-media":"/plugins"} className="group rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 transition hover:-translate-y-1 hover:border-cyan-300/25"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/[0.05]"><Icon className="h-5 w-5 text-cyan-300"/></div><span className="rounded-full border border-cyan-300/15 bg-cyan-300/[0.05] px-2 py-1 text-[8px] font-bold tracking-widest text-cyan-200/60">{state}</span></div><div className="mt-5 text-[9px] font-bold uppercase tracking-[0.25em] text-cyan-300/60">{id}</div><div className="mt-1 text-lg font-semibold">{title}</div><p className="mt-2 text-xs leading-5 text-white/35">{text}</p><div className="mt-5 flex items-center gap-1 text-[9px] font-bold uppercase tracking-widest text-white/40 group-hover:text-cyan-200">Open plugin <ArrowUpRight className="h-3 w-3"/></div></Link>)}</section>
      <section className="mb-6 grid gap-3 lg:grid-cols-[1.2fr_.8fr]"><Panel><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.25em] text-cyan-300/55"><Zap className="h-3.5 w-3.5"/> Plugin Factory</div><h3 className="mt-3 text-xl font-semibold">Turn an approved idea into a business plugin.</h3><p className="mt-2 max-w-2xl text-xs leading-5 text-white/35">Idea → validation → business model → capability map → plugin specification → build → test → deploy → operate → learn → scale.</p><div className="mt-5 flex flex-wrap gap-2">{["Departments","Agents","Capabilities","Infrastructure","Revenue","Risk gates"].map(x=><span key={x} className="rounded-lg border border-white/[0.07] bg-black/20 px-2.5 py-1.5 text-[9px] font-bold uppercase tracking-widest text-white/40">{x}</span>)}</div></Panel><Panel><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.25em] text-cyan-300/55"><PhoneCall className="h-3.5 w-3.5"/> Restored capability</div><h3 className="mt-3 text-lg font-semibold">Telephone Agents</h3><p className="mt-2 text-xs leading-5 text-white/35">Operations capability restored as a dependency that any business plugin can declare.</p><div className="mt-4 flex items-center gap-2 text-[9px] font-bold uppercase tracking-widest text-amber-200/60"><LockKeyhole className="h-3 w-3"/> Credentials / external actions gated</div></Panel></section>
      <div className="mb-3 flex items-center justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[0.28em] text-cyan-300/55">Core Runtime</div><h3 className="mt-1 text-lg font-semibold">Command modules</h3></div><div className="hidden items-center gap-2 text-[9px] uppercase tracking-widest text-white/25 md:flex"><ScanLine className="h-3.5 w-3.5"/> telemetry cycle {String(boot).padStart(2,"0")}%</div></div>
      <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Link to="/chat" className="block rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 transition hover:border-cyan-300/30"><Terminal className="h-5 w-5 text-cyan-300"/><div className="mt-4 text-lg font-semibold">Command Console</div><p className="mt-2 text-xs leading-5 text-white/35">Direct control over the intelligence layer and execution.</p></Link><Link to="/sessions" className="block rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 transition hover:border-cyan-300/30"><Activity className="h-5 w-5 text-cyan-300"/><div className="mt-4 text-lg font-semibold">Operations Matrix</div><p className="mt-2 text-xs leading-5 text-white/35">Sessions, active work and operational state.</p></Link><Link to="/cron" className="block rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 transition hover:border-cyan-300/30"><Clock3 className="h-5 w-5 text-cyan-300"/><div className="mt-4 text-lg font-semibold">Autonomous Scheduler</div><p className="mt-2 text-xs leading-5 text-white/35">Persistent routines and scheduled execution.</p></Link><Link to="/analytics" className="block rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 transition hover:border-cyan-300/30"><Gauge className="h-5 w-5 text-cyan-300"/><div className="mt-4 text-lg font-semibold">Performance Intelligence</div><p className="mt-2 text-xs leading-5 text-white/35">Measure throughput and revenue-layer signals.</p></Link><Link to="/logs" className="block rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 transition hover:border-cyan-300/30"><FileText className="h-5 w-5 text-cyan-300"/><div className="mt-4 text-lg font-semibold">Black Box</div><p className="mt-2 text-xs leading-5 text-white/35">Forensic operational telemetry and audit trail.</p></Link><Panel><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.25em] text-white/30"><Cpu className="h-3.5 w-3.5"/> Intelligence fabric</div><div className="mt-4 grid gap-2">{[["LOCAL","Ollama / Qwen3"],["GATEWAY","Hermes " + (status?.version??"loading")],["SAFETY","Financial execution locked"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/[0.06] bg-black/20 p-3"><div className="text-[8px] font-bold tracking-[0.22em] text-white/25">{a}</div><div className="mt-1 text-xs font-medium text-white/65">{b}</div></div>)}</div></Panel></section>
    </main>
  </div>;
}
